name: README size guard

on:
  push:
    paths:
      - README.md
  pull_request:
    paths:
      - README.md

env:
  MAX_BYTES: "25000"

jobs:
  readme_size_guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - id: size
        run: echo "bytes=$(wc -c < README.md | tr -d '[:space:]')" >> "$GITHUB_OUTPUT"

      - id: enforce
        env:
          BYTES: ${{ steps.size.outputs.bytes }}
        run: |
          if [ "$BYTES" -gt "$MAX_BYTES" ]; then
            echo "## README.md ${BYTES} > ${MAX_BYTES}" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        env:
          BYTES: ${{ steps.size.outputs.bytes }}
          MAX_BYTES: ${{ env.MAX_BYTES }}
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `⚠️ README.md ${process.env.BYTES} > ${process.env.MAX_BYTES}.`
            })
